### ISSUE TITLE
NoMethodError when trying to access Magento resolvable errors

### ISSUE THREAD

**Issue by dstotz** [springboardretail/springboard-client-ruby#10]
When accesing the endpoint /api/integrations/magento/connections/2/resolvable_errors I get a NoMethodError for each_pair

![image](https://cloud.githubusercontent.com/assets/9381594/14929659/9a885772-0e2c-11e6-8136-535e989b167c.png)

**Comment by jstotz** [comment]
@dstotz Can you post the results of calling `get.raw_body` instead?

**Comment by dstotz** [comment]
`"[{\"message\":\"Some items could not be imported\",\"resolve_url\":\"/#items/imports/71/status\"},{\"message\":\"Some items could not be imported\",\"resolve_url\":\"/#items/imports/70/status\"},{\"message\":\"Some items could not be imported\",\"resolve_url\":\"/#items/imports/82/status\"},{\"message\":\"Some items could not be imported\",\"resolve_url\":\"/#items/imports/92/status\"},{\"message\":\"Some items could not be imported\",\"resolve_url\":\"/#items/imports/80/status\"},{\"message\":\"Some items could not be imported\",\"resolve_url\":\"/#items/imports/85/status\"},{\"message\":\"Some items could not be imported\",\"resolve_url\":\"/#items/imports/78/status\"},{\"message\":\"Some items could not be imported\",\"resolve_url\":\"/#items/imports/79/status\"},{\"message\":\"Some items could not be imported\",\"resolve_url\":\"/#items/imports/84/status\"},{\"message\":\"Some items could not be imported\",\"resolve_url\":\"/#items/imports/93/status\"}]"`


![image](https://cloud.githubusercontent.com/assets/9381594/14930785/9779dee0-0e34-11e6-8cdb-7a3cbf742d5d.png)
