### ISSUE TITLE
Remove dependency on addressable

### ISSUE THREAD

**Issue by jstotz** [springboardretail/springboard-client-ruby#19]

**Comment by dstotz** [comment]
Resolved with #20

**Comment by DyegoCosta** [comment]
@dstotz @jstotz looks like we didn't publish a patch with this fix

**Comment by jstotz** [comment]
@DyegoCosta yeah, @dstotz is just doing some additional testing this morning. If all goes well we'll release a new gem version today.

**Comment by dstotz** [comment]
@jstotz @DyegoCosta I ran a bunch of scripts this morning including sales history imports and everything has been working just fine for me. I think we are good to go. If there is an issue, it has not presented itself yet.
